# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly Galleon feature-packs for Glow - PR and Nightly CI to test against WildFly SNAPSHOT build

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, reopened, ready_for_review]
env:
  WILDFLY_GLOW: https://github.com/wildfly/wildfly-glow/releases/download/1.0.5.Final/wildfly-glow-1.0.5.Final.zip
jobs:
  WildFly-build:
    uses: wildfly/wildfly/.github/workflows/shared-wildfly-build.yml@main
    with:
      wildfly-branch: main
      wildfly-repo: "wildfly/wildfly"
  build:
    name: ${{ matrix.os }}-jdk${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    needs: [WildFly-build]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['17', '21']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: wildfly-maven-repository
          path: .
      - name: Extract Maven Repo
        shell: bash
        run: tar -xzf wildfly-maven-repository.tar.gz -C ~
      - name: Download wildfly-glow
        run: |
          wget ${{ env.WILDFLY_GLOW }}
          unzip wildfly-glow*.zip -d .
          glowDir=$(find $PWD -type d -iname "wildfly-glow*")
          echo "WILDFLY_GLOW_DIR=$glowDir" >> "$GITHUB_ENV"
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Test
        run: bash tests/run-wildfly-glow-tests.sh
        shell: bash